version: '3'

services:
  flask-app:
    build:
      context: ./backend  
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    command: sh -c "sleep 2 && python main.py" 
    networks:
      - mynet

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: base_datos
    ports:
      - "5432:5432"
    networks:
      - mynet

  frontend:
    build:
      context: ./frontend
    expose:
      - "80"  
    networks:
      - mynet

  nginx:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./nginx/mynginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx_config/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
        - flask-app
        - frontend
    networks:
        - mynet


networks:
  mynet:
