version: '3'

services:
  flask-app:
    build:
      context: ./backend  
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    command: sh -c "sleep 2 && python main.py" 
    networks:
      - mynet

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: base_datos
    ports:
      - "5432:5432"
    networks:
      - mynet

  frontend:
    build:
      context: ./frontend
    expose:
      - "80"  # Exponer el puerto 80 internamente
    networks:
      - mynet

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Mapear el puerto 8080 externamente al puerto 80 interno de Nginx
    volumes:
      - ./nginx/mynginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
      - frontend
    networks:
      - mynet

networks:
  mynet:
